### ISSUE TITLE
benchmarks not running with gammapy-0.18.2

### ISSUE THREAD

**Issue by joveh** [gammapy/gammapy-benchmarks#113]
my setup:
```
curl -O https://gammapy.org/download/install/gammapy-0.18.2-environment.yml
conda env create -f gammapy-0.18.2-environment.yml
conda activate gammapy-0.18.2
pip install psrecord
gammapy download datasets
```

```
gammapy info

System:

	python_executable      : /home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/bin/python 
	python_version         : 3.7.0      
	machine                : x86_64     
	system                 : Linux      


Gammapy package:

	version                : 0.18.2     
	path                   : /home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/gammapy 


Other packages:

	numpy                  : 1.19.4     
	scipy                  : 1.4.1      
	astropy                : 4.1        
	regions                : 0.4        
	click                  : 7.0        
	yaml                   : 5.2        
	IPython                : 7.10.1     
	jupyterlab             : 2.0.1      
	matplotlib             : 3.2.1      
	pandas                 : 0.25.3     
	healpy                 : 1.13.0     
	iminuit                : 1.3.8      
	sherpa                 : 4.12.0     
	naima                  : not installed 
	emcee                  : 2.2.1      
	corner                 : 2.0.1      
	parfive                : 1.0.2      


Gammapy environment variables:

	GAMMAPY_DATA           : /home/vault/unrz/unrz009h/gammapy-datasets 
```

io is working
```python make.py run-benchmark io
INFO:__main__:Executing command: python /home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/io.py
io.py:46: Running io.py with N_OBS = 10
io.py:47: cwd = /tmp/1545732.eadm/tmpbsabd9cb
Process finished (6.28 seconds)
INFO:__main__:Writing results/io/results.txt
INFO:__main__:Writing results/io/results.png
INFO:__main__:Writing results/io/provenance.yaml
INFO:__main__:Writing results/results.yaml
```

analysis_3d not working
```
python make.py run-benchmark analysis_3d
INFO:__main__:Executing command: python /home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/analysis_3d.py
Invalid unit found in background table! Assuming (s-1 MeV-1 sr-1)
Invalid unit found in background table! Assuming (s-1 MeV-1 sr-1)
Invalid unit found in background table! Assuming (s-1 MeV-1 sr-1)
/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/astropy/units/quantity.py:477: RuntimeWarning: invalid value encountered in true_divide
  result = super().__array_ufunc__(function, method, *arrays, **kwargs)
  result = super().__array_ufunc__(function, method, *arrays, **kwargs)
Traceback (most recent call last):
  File "/home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/analysis_3d.py", line 118, in <module>
    run_benchmark()
  File "/home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/analysis_3d.py", line 107, in run_benchmark
    data_fit(stacked)
  File "/home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/analysis_3d.py", line 79, in data_fit
    fit = Fit(optimize_opts={"print_level": 1})
TypeError: __init__() got an unexpected keyword argument 'optimize_opts'
Process finished (60.44 seconds)
Traceback (most recent call last):
  File "make.py", line 146, in <module>
    cli()
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "make.py", line 108, in run_benchmarks
    **MONITOR_OPTIONS,
  File "make.py", line 142, in run_single_benchmark
    shutil.copyfile(Path(path) / "bench.yaml", f"results/{benchmark}/bench.yaml")
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpchtlunfm/bench.yaml'

```
analysis_3d_joint 
```
python make.py run-benchmark analysis_3d_joint
INFO:__main__:Executing command: python /home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/analysis_3d_joint.py
Invalid unit found in background table! Assuming (s-1 MeV-1 sr-1)
Traceback (most recent call last):
  File "/home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/analysis_3d_joint.py", line 125, in <module>
    run_benchmark()
  File "/home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/analysis_3d_joint.py", line 114, in run_benchmark
    data_fit(datasets)
  File "/home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/analysis_3d_joint.py", line 86, in data_fit
    fit = Fit()
TypeError: __init__() missing 1 required positional argument: 'datasets'
Process finished (128.22 seconds)
Traceback (most recent call last):
  File "make.py", line 146, in <module>
    cli()
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "make.py", line 108, in run_benchmarks
    **MONITOR_OPTIONS,
  File "make.py", line 142, in run_single_benchmark
    shutil.copyfile(Path(path) / "bench.yaml", f"results/{benchmark}/bench.yaml")
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpokzbe12p/bench.yaml'
```
lightcurve_1d
```
python make.py run-benchmark lightcurve_1d
INFO:__main__:Executing command: python /home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/lightcurve_1d.py
Invalid unit found in background table! Assuming (s-1 MeV-1 sr-1)
/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/astropy/units/quantity.py:477: RuntimeWarning: overflow encountered in exp
  result = super().__array_ufunc__(function, method, *arrays, **kwargs)
/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/astropy/units/quantity.py:477: RuntimeWarning: invalid value encountered in subtract
  result = super().__array_ufunc__(function, method, *arrays, **kwargs)
Traceback (most recent call last):
  File "/home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/lightcurve_1d.py", line 136, in <module>
    run_benchmark()
  File "/home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/lightcurve_1d.py", line 120, in run_benchmark
    datasets = simulate()
  File "/home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/lightcurve_1d.py", line 72, in simulate
    name=f"dataset_{i}",
TypeError: create() got an unexpected keyword argument 'geom'
Process finished (4.16 seconds)
Traceback (most recent call last):
  File "make.py", line 146, in <module>
    cli()
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "make.py", line 108, in run_benchmarks
    **MONITOR_OPTIONS,
  File "make.py", line 142, in run_single_benchmark
    shutil.copyfile(Path(path) / "bench.yaml", f"results/{benchmark}/bench.yaml")
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/1545732.eadm/tmp4rd9g4ed/bench.yaml'
```
lightcurve_3d
```
python make.py run-benchmark lightcurve_3d
INFO:__main__:Executing command: python /home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/lightcurve_3d.py
Invalid unit found in background table! Assuming (s-1 MeV-1 sr-1)
/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/astropy/units/quantity.py:477: RuntimeWarning: overflow encountered in exp
  result = super().__array_ufunc__(function, method, *arrays, **kwargs)
/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/astropy/units/quantity.py:477: RuntimeWarning: invalid value encountered in subtract
  result = super().__array_ufunc__(function, method, *arrays, **kwargs)
Traceback (most recent call last):
  File "/home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/lightcurve_3d.py", line 157, in <module>
    run_benchmark()
  File "/home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/lightcurve_3d.py", line 145, in run_benchmark
    get_lc(datasets)
  File "/home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/lightcurve_3d.py", line 105, in get_lc
    print(lc.to_table(format="lightcurve", sed_type="flux")["flux"])
AttributeError: 'LightCurve' object has no attribute 'to_table'
Process finished (134.81 seconds)
Traceback (most recent call last):
  File "make.py", line 146, in <module>
    cli()
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "make.py", line 108, in run_benchmarks
    **MONITOR_OPTIONS,
  File "make.py", line 142, in run_single_benchmark
    shutil.copyfile(Path(path) / "bench.yaml", f"results/{benchmark}/bench.yaml")
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpzfnuy02c/bench.yaml'
```
spectrum_1d
```
python make.py run-benchmark spectrum_1d
INFO:__main__:Executing command: python /home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/spectrum_1d.py
Traceback (most recent call last):
  File "/home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/spectrum_1d.py", line 143, in <module>
    run_benchmark()
  File "/home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/spectrum_1d.py", line 120, in run_benchmark
    stacked = data_prep()
  File "/home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/spectrum_1d.py", line 55, in data_prep
    stacked = SpectrumDatasetOnOff.create(geom=geom, energy_axis_true=e_true, name="stacked")
TypeError: create() got an unexpected keyword argument 'geom'
Process finished (4.18 seconds)
Traceback (most recent call last):
  File "make.py", line 146, in <module>
    cli()
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "make.py", line 108, in run_benchmarks
    **MONITOR_OPTIONS,
  File "make.py", line 142, in run_single_benchmark
    shutil.copyfile(Path(path) / "bench.yaml", f"results/{benchmark}/bench.yaml")
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp3m7smbxv/bench.yaml'
```
spectrum_1d_joint
```
python make.py run-benchmark spectrum_1d_joint
INFO:__main__:Executing command: python /home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/spectrum_1d_joint.py
Traceback (most recent call last):
  File "/home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/spectrum_1d_joint.py", line 140, in <module>
    run_benchmark()
  File "/home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/spectrum_1d_joint.py", line 117, in run_benchmark
    datasets = data_prep()
  File "/home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/spectrum_1d_joint.py", line 54, in data_prep
    empty = SpectrumDatasetOnOff.create(geom, energy_axis_true=e_true)
TypeError: create() got an unexpected keyword argument 'energy_axis_true'
Process finished (3.65 seconds)
Traceback (most recent call last):
  File "make.py", line 146, in <module>
    cli()
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "make.py", line 108, in run_benchmarks
    **MONITOR_OPTIONS,
  File "make.py", line 142, in run_single_benchmark
    shutil.copyfile(Path(path) / "bench.yaml", f"results/{benchmark}/bench.yaml")
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpo4w58b54/bench.yaml'
```
tsmap_estimator
```
python make.py run-benchmark tsmap_estimator
INFO:__main__:Executing command: python /home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/tsmap_estimator.py
WARNING: FITSFixedWarning: 'datfix' made the change 'Set DATEREF to '2001-01-01T00:01:04.184' from MJDREF.
Set MJD-OBS to 54682.655283 from DATE-OBS.
Set MJD-END to 57236.967546 from DATE-END'. [astropy.wcs.wcs]
Traceback (most recent call last):
  File "/home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/tsmap_estimator.py", line 89, in <module>
    run_benchmark()
  File "/home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/tsmap_estimator.py", line 72, in run_benchmark
    data = data_prep()
  File "/home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/tsmap_estimator.py", line 30, in data_prep
    "$GAMMAPY_DATA/fermi-3fhl-gc/fermi-3fhl-gc-psf-cube.fits.gz", format="gtpsf"
TypeError: read() got an unexpected keyword argument 'format'
Process finished (15.14 seconds)
Traceback (most recent call last):
  File "make.py", line 146, in <module>
    cli()
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "make.py", line 108, in run_benchmarks
    **MONITOR_OPTIONS,
  File "make.py", line 142, in run_single_benchmark
    shutil.copyfile(Path(path) / "bench.yaml", f"results/{benchmark}/bench.yaml")
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpqv60pod_/bench.yaml'
```
ring_background_estimator
```
python make.py run-benchmark ring_background_estimator
INFO:__main__:Executing command: python /home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/ring_background_estimator.py
Traceback (most recent call last):
  File "/home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/ring_background_estimator.py", line 139, in <module>
    run_benchmark()
  File "/home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/ring_background_estimator.py", line 120, in run_benchmark
    analysis = data_prep()
  File "/home/vault/unrz/unrz009h/gammapy-benchmarks-master/benchmarks/ring_background_estimator.py", line 33, in data_prep
    config.datasets.geom.wcs.width = {"width": "3 deg", "height": "3 deg"}
  File "pydantic/main.py", line 281, in pydantic.main.BaseModel.__setattr__
ValueError: "WcsConfig" object has no field "width"
Process finished (4.17 seconds)
Traceback (most recent call last):
  File "make.py", line 146, in <module>
    cli()
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "make.py", line 108, in run_benchmarks
    **MONITOR_OPTIONS,
  File "make.py", line 142, in run_single_benchmark
    shutil.copyfile(Path(path) / "bench.yaml", f"results/{benchmark}/bench.yaml")
  File "/home/hpc/unrz/unrz009h/.conda/envs/gammapy-0.18.2/lib/python3.7/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpffh2wrnd/bench.yaml'
```

Any advice on how to fix the issue?

**Comment by registerrier** [comment]
Hello @joveh . The gammapy-benchmarks are designed to work with the dev version of gammapy. There is no tagged version that match a given gammapy release.
To make them run, you have to install the dev version of gammapy.

**Comment by joveh** [comment]
Thanks for the quick answer.
I am a gammapy noob and just try to look at some cluster monitoring of gammapy jobs.
Could you point me to the dev version?

**Comment by registerrier** [comment]
You can find in the developer documentation some indication on how to fork the repository and clone your fork. See:
https://docs.gammapy.org/0.18.2/development/intro.html#get-set-up

If you don't intend to contribute for now, you can simply clone the main repository and install the environment. To so do so:
```
git clone https://github.com/gammapy/gammapy.git
cd gammapy
conda env create -f environment-dev.yml
source activate gammapy-dev
pip install -e .
```

Question to @adonath @Bultako @QRemy : do you think we should keep tagged version of the benchmarks for specific releases?

**Comment by adonath** [comment]
I have never thought about this. I think from our perspective it does not make sense for now, because we do not back port changes to tagged releases. However after v1.0 it could make sense to do this. So keep a benchmark / validation chain running for v1.0 the check for bug fix releases such v1.0.1 etc.
